---
name: TestPlugin
version: 0.0.0
main: rstk\TestPlugin\Main
api: 3.21.1
author: rstk
description: "test plugin"

commands:
        testCommand:
                description: "test command"
                aliases: [testCommandAlias]
                permission: example.command
permissions:
        example.command:
                description: "test command permission"
                default: op
...
