name: steak
version: 0.0.1
main: rstk\steak\Main
api: 3.21.1
author: rstk
description: the /steak command

commands:
  steak:
    description: Get steaks
    permission: perms.all

permissions:
  steak.perms.all:
    description: Permissions for all players
    default: true
  
  steak.perms.op:
    description: Permissions for operators
    default: op
